### ISSUE TITLE
Evaluation against multilingual BERT?

### ISSUE THREAD

**Issue by jbingel** [mollerhoj/danish_bert#1]
Thanks a lot for this, great to see!

Do you have an idea of how well your model does compared to multilingual BERT?

**Comment by mollerhoj** [comment]
You're welcome!

Not really - do you know of any good publish danish dataset I could evaluate with? That would certainly be very interesting.

**Comment by jbingel** [comment]
One idea would be to compare downstream performance, e.g. using a BERT-based parser or POS tagger on the UD dataset (based on DDT afaik).

You could of course also measure perplexity on raw text.

**Comment by hvingelby** [comment]
This is great work @mollerhoj!

We have just finished a bunch of experiments using the Multilingual BERT on our Named Entity annotations of the DDT achieving ~85 F1 score on LOC, ORG and PER.

I will post an update when the final dataset is uploaded to the danlp repository together with the results :+1:

**Comment by mollerhoj** [comment]
@hvingelby Thank you :-) that sounds like it would be a good candidate for evaluation - would it be possible for you to check what performance you can achieve with this model?

**Comment by hvingelby** [comment]
@mollerhoj yes I will do that when I get the time for it. It would be very interesting to see if the BERT trained purely on Danish is better.

What we found was that using a Norwegian NER dataset together with our Danish data yielded the best performance, but this cross-lingual transfer was of course only possible due to the multilingual representations.

**Comment by mollerhoj** [comment]
@hvingelby Right, I actually considered appending Norwegian data to my current dataset, as the two languages are so similar in writing. Perhaps a future version of this repo should be a combination of the two. Let me know what you find.
