### ISSUE TITLE
As far as I can tell, no one has gotten the Norwegian model to work

### ISSUE THREAD

**Issue by Sleemanmunk** [mollerhoj/danish_bert#11]
I ran into breaking issues just trying to get the much-hyped Norwegian BERT language model to run at all. I submitted a bug about this that has been thoroughly ignored. I looked around on the web and haven't found any evidence that anyone has gotten good results out of this model. Jens Dahl Møllerhøj, I see you bragging about this work in [interviews](https://jaxenter.com/nlp-bert-danish-swedish-norwegian-172029.html). Do you think you might be able to offer a little more detail as to how to properly take advantage of this model you're so proud of?

**Comment by mollerhoj** [comment]
Like many other github repos, the code and models here are provided for free, but do not come with the support you might expect from commercial software. I'll will look into providing a tutorial for using the BERT models, but I cannot make any promises as to when as I do not know when my schedule will allow it.

Given the tone of this issue, I will close it. I refer to this research as documentation for the results of the models: https://www.aclweb.org/anthology/2020.lrec-1.565/.
