### ISSUE TITLE
Issues with tokenizer altering chars

### ISSUE THREAD

**Issue by christianbv** [mollerhoj/danish_bert#13]
Hey, 

I've downloaded the norwegian model and used in the package hugging-face, but I have some problems with the BertTokenizer class, as it weirdly enough changes all "å" characters to "a", whereas the chars "æ" and "ø" remains the same? Any idea why this may be so? 

Thanks, Christian

**Comment by kasperjunge** [comment]
I have note tried the Norwegian one, but it is not a a problem with the danish pre-trained model? 🤔
![billede](https://user-images.githubusercontent.com/39537120/91552763-a2f4b380-e92c-11ea-896a-208d3db86475.png)

**Comment by kasperjunge** [comment]
Actually I just noticed that the word "ubetrådt" is tokenized as: [ 'ubet', '##rad', '##t']. But it does a good job with the other æøå's

**Comment by christianbv** [comment]
I managed to fix it, just forgot to close the issue - just use fasttokenizer and disable strip-accents. The danish model is not crooked and has a different vocab file so I guess it is not a problem there :)
