### ISSUE TITLE
vocab_size == 32000 but vocab.txt is length 31748

### ISSUE THREAD

**Issue by emillykkejensen** [mollerhoj/danish_bert#3]
In bert_config.json vocab_size is set to 32000 but if I have a look in the vocab.txt file there are only 31748 word pieces?

**Comment by mollerhoj** [comment]
Good question: We've intensionally left room for words with domain specific characters. (e.g. you could add ū to the vocab file and then fine-tune on your own corpus to learn weights for the wordpiece)
