### ISSUE TITLE
Cased Model?

### ISSUE THREAD

**Issue by TharinduDR** [mollerhoj/danish_bert#7]
Are you going to release a danish-base-cased model?

**Comment by mollerhoj** [comment]
We have no plans for that at the moment, could you describe your use case?

**Comment by TharinduDR** [comment]
Hi @mollerhoj,

I was using the Danish Version 1 model in an Aggression Detection task for Danish. However, the results were slightly worse than bert-multilingual-cased model. I believe for a task like aggression detection case matters. (For English - I assumed it might be the case for Danish too - I don't know Danish - I only use language models). 

However, I will try the Danish version 2 too and will let you know.

**Comment by mollerhoj** [comment]
That is a very reasonable assumption I must admit. I'll be considering cased models in the future.
