### ISSUE TITLE
[suggestion] Upload models to HuggingFace transformer database

### ISSUE THREAD

**Issue by saattrupdan** [mollerhoj/danish_bert#8]
The NLP startup [HuggingFace](https://huggingface.co/) is specialising in [transformer models](https://github.com/huggingface/transformers), and they've created a database full of pretrained models, to which you might be interested in uploading your models as well:

https://huggingface.co/models

It would then be simple to use your models, using their `transformers` python library:
```python
from transformers import AutoTokenizer, AutoModelWithLMHead
tokenizer = AutoTokenizer.from_pretrained("botxo/danish_bert_uncased_v2")
model = AutoModelWithLMHead.from_pretrained("botxo/danish_bert_uncased_v2")
```
There are already a decent chunk of Swedish models and a couple of Finnish ones, but no Danish or Norwegian ones yet. 

This is just a heads up in case you didn't already know about this! (I'm not affliated with HuggingFace in any way)

**Comment by mollerhoj** [comment]
Thanks for the suggestion! We're still considering how to best publish these models. Training them requires significant resources, so business understandably wants to ensure that we're receiving some form of recognition. This will be an ongoing discussion on our part - but in short, it's a business decision.

**Comment by AngledLuffa** [comment]
To follow up on this, is there a possibility of seeing these models on HuggingFace?  It's a super convenient way to organize all of the transformers in the world, although admittedly the only exposure Certainly would get would be the name of the model

**Comment by saattrupdan** [comment]
> To follow up on this, is there a possibility of seeing these models on HuggingFace?  It's a super convenient way to organize all of the transformers in the world, although admittedly the only exposure Certainly would get would be the name of the model

The Danish model was published at https://huggingface.co/Maltehb/danish-bert-botxo (BotXO was Certainly's previous name). Not sure about the others.

**Comment by AngledLuffa** [comment]
excellent, ty!
